In [3]:
 # 直接写变量名，会自动显示值，不需要 print()
name = "王彦华"
years = 8
name, years

('王彦华', 8)

In [6]:
import pandas as pd

data = {
      "语言": ["Java", "Python", "SQL"],
      "熟练度": [90, 30, 60],
      "优先级": ["维持", "重点学", "重点学"]
}
df = pd.DataFrame(data)
df  # Notebook 里 DataFrame 会渲染成漂亮的表格

       语言  熟练度  优先级
0    Java   90   维持
1  Python   30  重点学
2     SQL   60  重点学

In [7]:
# 筛选需要重点学的技术
df[df["优先级"] == "重点学"]

       语言  熟练度  优先级
1  Python   30  重点学
2     SQL   60  重点学

In [8]:
df["熟练度"].mean()

np.float64(60.0)